baseURL: "https://suneel-sarswat.github.io"
languageCode: "en-us"
title: "Dr. Suneel Sarswat"
theme: hugo-profile

outputs:
  home: ["HTML","RSS","JSON"]
  page: ["HTML","RSS"]
enableRobotsTXT: true

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      url: /gallery
      weight: 2
    - identifier: about
      name: Full About
      url: /about
      weight: 3

params:
  title: "Dr. Suneel Sarswat"
  description: "Formal Verification • Financial Systems  • Quantitative Finance and ML"
  favicon: "/favicon.ico"

  useBootstrapCDN: false
  mathjax: true
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light"

  font:
    fontSize: 1.115rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left
    fontFamily: "JetBrains Mono"

  color:
    textColor: "#1a1a1a"
    secondaryTextColor: "#6c757d"
    textLinkColor: "#003366"
    backgroundColor: "#ffffff"
    secondaryBackgroundColor: "#f7f7f7"
    primaryColor: "#003366"
    secondaryColor: "#f7f7f7"
    darkmode:
      textColor: "#e4e6eb"
      secondaryTextColor: "#b0b3b8"
      textLinkColor: "#ffffff"
      backgroundColor: "#18191a"
      secondaryBackgroundColor: "#212529"
      primaryColor: "#ffffff"
      secondaryColor: "#212529"

  navbar:
    align: ms-auto
    brandName: "Dr. Suneel Sarswat"
    disableSearch: false
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  sections:
    - home
    - about
    - education
    - experience
    - projects
    - achievements
    - contact

  hero:
    enable: true
    intro: "Hello, I’m"
    title: "Dr. Suneel Sarswat"
    subtitle: "Formal Verification • Regulatory Technology • Quantitative Finance"
    content: "I bridge rigorous theory and live-market reality through verified software and regulatory consulting."
    image: /images/hero.svg
    bottomImage:
      enable: true
    button:
      enable: true
      name: "CV"
      url: "/files/cv.pdf"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/suneel-sarswat"
        - icon: fab fa-linkedin
          url: "https://linkedin.com/in/suneel-sarswat"
        - icon: fab fa-twitter
          url: "https://twitter.com/suneel_sarswat"

  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      Dr. Suneel Sarswat is a computer scientist and quantitative-finance expert specialising in the formal verification of financial systems. His PhD research at TIFR produced the first fully-verified checker for exchange logs and six top-tier publications. He has consulted for the Ministry of Finance and SEBI on regulatory technology and has trained 500+ professionals from RBI, SEBI, NSE and BSE in advanced analytics and fraud-detection techniques.
    skills:
      enable: true
      title: "Expertise"
      items:
        - "Trading system at exchanges"
        - "Formal Verification (Rocq/Coq)"
        - "Double auctions"
        - "Market-Surveillance Systems"
        - "Machine Learning in Finance"
        - "Quantitative Risk Analytics"

  experience:
    enable: true
    items:
      - job: "Adjunct Faculty"
        company: "National Institute of Securities Markets (NISM)"
        companyUrl: "https://www.nism.ac.in"
        date: "2012 – Present"
        content: "Design and deliver executive programmes on quantitative finance and machine-learning applications in capital markets."
      - job: "Analytics Consultant"
        company: "Private Analytics Firms"
        date: "2020 – 2024"
        content: "Guide machine-learning engineers team on client projects."
      - job: "Research Analyst"
        company: "Bank of America"
        companyUrl: "https://www.bankofamerica.com"
        date: "2006 – 2009"
        content: "Developed quantitative models for derivatives pricing and risk analytics."

  education:
    enable: true
    items:
      - title: "PhD in Computer Science"
        school:
          name: "Tata Institute of Fundamental Research (TIFR), Mumbai"
          url: "https://www.tifr.res.in"
        date: "2024"
        content: "Dissertation: Formal Verification of Financial Systems"
      - title: "M.S. in Computer Science"
        school:
          name: "Tata Institute of Fundamental Research (TIFR), Mumbai"
          url: "https://www.tifr.res.in"
        date: "2015"
      - title: "M.Sc. in Applied Statistics"
        school:
          name: "Indian Institute of Technology (IIT), Mumbai"
          url: "https://www.iitb.ac.in"
        date: "2005"

  projects:
    enable: true
    items:
      - title: "Verified Exchange-Log Checker"
        content: "25 000+ lines Rocq implementation; first fully-verified checker for real-world exchange logs."
        image: /images/projects/checker.jpg
        badges: ["Rocq/Coq", "OCaml", "Formal Methods"]
        links:
          - icon: fab fa-github
            url: "https://github.com/suneel-sarswat/exchange-checker"
      - title: "SEBI Market-Manipulation Detector"
        content: "Clustering-based ML pipeline deployed as part of SEBI’s surveillance system."
        badges: ["Python", "Scikit-learn", "BigQuery"]
      - title: "Credit-Rating-Agency Policy Report"
        content: "Policy paper delivered to the Ministry of Finance with neural-network evaluation framework."
        badges: ["Policy", "Neural Networks", "Python"]

  achievements:
    enable: true
    items:
      - title: "Top-Tier Publications"
        content: "Co-authored 6 papers at premier CS conferences (CAV, FM, TACAS)."
        image: /images/achievement.jpg
      - title: "Study Group Mathematics with Industry"
        content: "Invited participant at Eindhoven University of Technology."
        image: /images/achievement.jpg
      - title: "500+ Professionals Trained"
        content: "Designed curricula for RBI, SEBI, NSE, BSE and major banks."
        image: /images/achievement.jpg

  contact:
    enable: true
    content: "Have a question or collaboration idea? My inbox is always open."
    btnName: "Email Me"
    btnLink: "mailto:suneel.sarswat@gmail.com"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
    socialNetworks:
      github: "https://github.com/suneel-sarswat"
      linkedin: "https://www.linkedin.com/in/suneel-sarswat-3398a86/"
      twitter: "https://twitter.com/"
