baseURL: "https://suneel-sarswat.github.io"
languageCode: "en-us"
title: "Dr. Suneel Sarswat"
theme: hugo-profile

outputs:
  home: ["HTML","RSS","JSON"]
  page: ["HTML","RSS"]
enableRobotsTXT: true

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
#    - identifier: blog
#      name: Blog
#      title: Latest posts
#      url: /blogs
#      weight: 1
    - identifier: about
      name: CV / About
      title: CV download
      url: /files/cv.pdf
      weight: 2

params:
  title: "Dr. Suneel Sarswat"
  description: "Formal Verification • Regulatory Technology • Quantitative Finance"
  favicon: "/favicon.ico"
  backgroundDots: true   # to removes the 16 '+' dots, make this false

  useBootstrapCDN: false
  mathjax: true
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light"

  font:
    fontSize: 1.115rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left
    fontFamily: "JetBrains Mono"

  color:
    textColor: "#1a1a1a"
    secondaryTextColor: "#6c757d"
    textLinkColor: "#003366"
    backgroundColor: "#ffffff"
    secondaryBackgroundColor: "#f7f7f7"
    primaryColor: "#003366"
    secondaryColor: "#f7f7f7"
    darkmode:
      textColor: "#e4e6eb"
      secondaryTextColor: "#b0b3b8"
      textLinkColor: "#ffffff"
      backgroundColor: "#18191a"
      secondaryBackgroundColor: "#212529"
      primaryColor: "#ffffff"
      secondaryColor: "#212529"

  navbar:
    align: ms-auto
    brandName: "Dr. Suneel Sarswat"
    disableSearch: false
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disablePublications: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  sections:
    - home
    - about
    - publications
    - education
    - experience
    - projects
    - achievements
    - contact

  hero:
    enable: true
    intro: "Hello, I’m"
    title: "Dr. Suneel Sarswat"
    subtitle: "Formal Verification • Regulatory Technology • Quantitative Finance"
    content: "I build mathematically-verified compliance tools for financial markets."
    image: images/me.jpg
    bottomImage:
      enable: true
    button:
      enable: true
      name: "About & CV"
      url: "/about"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/suneel-sarswat"
        - icon: fab fa-linkedin
          url: "https://linkedin.com/in/suneel-sarswat"
        - icon: fab fa-twitter
          url: "https://twitter.com/suneel_sarswat"

  about:
    enable: true
    title: "About Me"
#    image: "/images/me.jpg"
    content: |-
      Dr. Suneel Sarswat is a computer-scientist and regulatory-technology expert specialising in formal verification of financial systems.  His PhD work at TIFR produced the world’s first fully-verified exchange-matching compliance checker (25 000+ lines of Rocq code) and six top-tier publications.  He has consulted for the Ministry of Finance and SEBI on market-surveillance algorithms and has trained 500+ regulators and bankers in advanced analytics.

    skills:
      enable: true
      title: "Expertise"
      items:
        - "Formal Verification (Coq/Rocq)"
        - "Market-Surveillance Systems"
        - "Reg-Tech & Compliance"
        - "Python, R, OCaml"
        - "ML in Finance"
        - "Risk Analytics"

  experience:
    enable: true
    items:
      - job: "Adjunct Faculty"
        company: "National Institute of Securities Markets (NISM)"
        companyUrl: "https://www.nism.ac.in"
        date: "2009–2012, 2019–Present"
        content: "Design and deliver executive programmes on quantitative finance, data analysis and ML in capital markets."
      - job: "Analytics Consultant"
        company: "Decimal Point Analytics"
        companyUrl: "https://decimalpointanalytics.com/"
        date: "2020–2024"
        content: "Led machine-learning engagements for market-manipulation detection and credit-risk modelling."
      - job: "Research Scholar"
        company: "Tata Institute of Fundamental Research (TIFR)"
        companyUrl: "https://www.tcs.tifr.res.in/web/"
        date: "2012–2017"
	content: "PhD research on verified exchange-matching algorithms; 25 k+ lines Coq code, 6 premier venue papers."
      - job: "Research Analyst"
        company: "Bank of America"
        companyUrl: "https://www.ml.com/wealthmanagement.html"
        date: "2006–2009"
        content: "Developed/back-tested quantitative derivatives-pricing and risk-analytics models."

  education:
    enable: true
    items:
      - title: "PhD in Computer Science"
        school:
          name: "Tata Institute of Fundamental Research (TIFR), Mumbai"
          url: "https://www.tifr.res.in"
        date: "2024"
        content: "A Formal Approach to Exchange Design and Regulation"
      - title: "M.Sc. in Computer Science"
        school:
          name: "Tata Institute of Fundamental Research (TIFR), Mumbai"
          url: "https://www.tifr.res.in"
        date: "2015"
        content: "Conflict-free colouring of guards in polygons"
      - title: "M.Sc. in Applied Statistics"
        school:
          name: "Indian Institute of Technology (IIT), Mumbai"
          url: "https://www.iitb.ac.in"
        date: "2005"
	content: "Wavelet methods in time series"

  publications:
    enable: true
    items:
      - title: "PhD in Computer Science"
        school:
          name: "Tata Institute of Fundamental Research (TIFR), Mumbai"
          url: "https://www.tifr.res.in"
        date: "2024"
        content: "A Formal Approach to Exchange Design and Regulation"
      - title: "M.Sc. in Computer Science"
        school:
          name: "Tata Institute of Fundamental Research (TIFR), Mumbai"
          url: "https://www.tifr.res.in"
        date: "2015"
        content: "Conflict-free colouring of guards in polygons"
      - title: "M.Sc. in Applied Statistics"
        school:
          name: "Indian Institute of Technology (IIT), Mumbai"
          url: "https://www.iitb.ac.in"
        date: "2005"
	content: "Wavelet methods in time series"

  projects:
    enable: true
    items:
      - title: "Verified Exchange-Log Checker"
        content: "World’s first fully-verified compliance checker for exchange matching. 25 k+ lines Coq code, tested on real Indian exchange data."
        image: /images/checker.png
        badges: ["RegTech", "Coq/Rocq", "Formal Methods", "OCaml"]
      - title: "SEBI Market-Manipulation Detector"
        content: "Clustering-based ML pipeline integrated into SEBI surveillance systems."
        badges: ["Spectral Clustering", "Trade Logs", "Colluding Groups"]
      - title: "Credit-Rating-Agency Policy Report"
        content: "Policy paper delivered to the Ministry of Finance with neural-network evaluation framework."
        badges: ["Policy", "Neural Networks", "Credit Ratings"]

  achievements:
    enable: true
    items:
      - title: "ACM Second Prize – SRC"
        content: "International Conference on Functional Programming (2020)."
        image: /images/achievement.png
      - title: "500+ Professionals Trained"
        content: "RBI, SEBI, NSE, BSE and major banks."
        image: /images/training.png
      - title: "Study Group Mathematics with Industry"
        content: "Invited participant, Eindhoven University of Technology (TU/e)."
        image: /images/tue.png

  contact:
    enable: true
    content: "Have a question or collaboration idea? My inbox is always open."
    btnName: "Email Me"
    btnLink: "mailto:suneel.sarswat@gmail.com"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
    socialNetworks:
      github: "https://github.com/suneel-sarswat"
      linkedin: "https://www.linkedin.com/in/suneel-sarswat-3398a86/"


  singlePages:
    scrollprogress:
      enable: true   # keeps the thin scroll bar
    readTime:
      enable: true
      content: "min read"
